---

- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Create APT keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and process Nagios GPG key
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://repo.nagios.com/GPG-KEY-NAGIOS-V3 | gpg --dearmor -o /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg
  args:
    creates: /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg
  changed_when: false

- name: Add Nagios repository using deb822 format
  become: true
  ansible.builtin.deb822_repository:
    name: nagios
    types:
      - deb
    uris:
      - https://repo.nagios.com/deb/{{ ansible_distribution_release }}
    suites:
      - /
    signed_by: /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg
    state: present

- name: Update APT package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install NCPA package
  become: true
  ansible.builtin.apt:
    name: ncpa
    state: present
