---

- name: add apt key
  ansible.builtin.apt_key:
    url: https://repo.nagios.com/GPG-KEY-NAGIOS-V2
    state: present

- name: add nagios repository
  ansible.builtin.apt_repository:
    repo: deb https://repo.nagios.com/deb/{{ ansible_facts.distribution_release}} /
    state: present

- name: apt update cache
  apt:
    update_cache: yes

- name: install ncpa package
  apt:
    name: ncpa
    state: present
