---

- name: Add Nagios repository using deb822 format
  ansible.builtin.deb822_repository:
    name: nagios
    types:
      - deb
    uris:
      - https://repo.nagios.com/deb/{{ ansible_distribution_release }}
    suites:
      - /
    components:
      - main
    state: present
    update_cache: true
    gpg_key: https://repo.nagios.com/GPG-KEY-NAGIOS-V3

- name: install ncpa package
  ansible.builtin.apt:
    name: ncpa
    state: present
