---

- name: Add Nagios GPG key
  ansible.builtin.apt_key:
    url: https://repo.nagios.com/GPG-KEY-NAGIOS-V3
    state: present

- name: add nagios repository
  ansible.builtin.apt_repository:
    repo: "deb https://repo.nagios.com/deb/{{ ansible_distribution_release }} /"
    state: present
    filename: nagios
    update_cache: True

- name: install ncpa package
  ansible.builtin.apt:
    name: ncpa
    state: present
