---

- name: Install EPEL repository
  become: true
  ansible.builtin.package:
    name: "{{ epel_repo_urls[ansible_facts.distribution_major_version] }}"
    state: present
    disable_gpg_check: true

- name: Enable CodeReady Builder repository
  become: true
  ansible.builtin.command:
    cmd: "subscription-manager repos --enable {{ codeready_repos[ansible_facts.distribution_major_version] }}"
  when: ansible_facts.distribution == "RedHat"
  changed_when: false
  failed_when: false

- name: Add Nagios repository
  become: true
  ansible.builtin.package:
    name: "{{ nagios_repo_urls[ansible_facts.distribution_major_version] }}"
    state: present
    disable_gpg_check: true

- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true
  changed_when: false

- name: Install NCPA package
  become: true
  ansible.builtin.package:
    name: ncpa
    state: present
