---

- name: restarting ncpa
  systemd:
    name: ncpa.service
    state: restarted
    enabled: yes
  listen: restart ncpa

- name: check if ncpa is running
  uri:
    url: https://localhost:{{ __ncpa_config.listener.port }}/api?token={{ __ncpa_config.api.community_string }}
    validate_certs: no
  listen: restart ncpa
