---

- name: Restart NCPA service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: ncpa.service
    state: restarted
    enabled: true
  listen: restart ncpa

- name: Verify NCPA service is running
  ansible.builtin.uri:
    url: https://localhost:{{ __ncpa_config.listener.port }}/api?token={{ __ncpa_config.api.community_string }}
    validate_certs: false
    timeout: 30
  listen: restart ncpa
  retries: 3
  delay: 5
